name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Add host key to known_hosts
        run: ssh-keyscan -p 2221 181.191.104.6 >> ~/.ssh/known_hosts

      - name: Deploy code to server
        run: ssh -p 2221 root@181.191.104.6 "bash -s" < ./deploy.sh
